baseURL = 'https://BYTX-zyh.github.io/'
languageCode = 'zh'
title = '白衣踏雪'
theme = 'xmin'

enableGitInfo = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3
[[menu.main]]
name = "About"
url = "/About/"
weight = 4

[params]
syntaxHighlighter = "highlight.js"
description = "A website built through Hugo and blogdown."
footer = "&copy; [BYTX](https://BYTX-zyh.github.io)  2022 -- {Year} | [Github](https://github.com/BYTX-zyh) | [Rss](https://bytx-zyh.github.io//index.xml)"
GithubEdit = "https://github.com/BYTX-zyh/BYTX-zyh.github.io/edit/master/content/"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]


[outputs]
    home = ['html', 'rss']
    section = ['html', 'rss']
    taxonomy = ['html']
    term = ['html']

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
    unsafe = true ## 允许 Markdown 内嵌 html 代码
#[markup.highlight]
#    anchorLineNos = false
#    codeFences = true
#    guessSyntax = false
#    hl_Lines = ''
#    hl_inline = false
#    lineAnchors = ''
#    lineNoStart = 1
#    lineNos = true
#    lineNumbersInTable = true
#    noClasses = true
#    noHl = true
#    style = 'nord'`
#    tabWidth = 2


copyright = "2023 BYTX All rights reserved"
languageCode = "zh-cn"

[Author]
name = "BYTX-zyh"
email = "bytxzyh@gmail.com"