theme = "hugo-xmin"
baseURL = 'https://BYTX-zyh.github.io'
languageCode = 'en-us'
title = 'My New Hugo Site'
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
[[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 4